name: Build and Push to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (with session token)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push WEB image
        env:
          ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO: ${{ secrets.ECR_WEB_REPO }}
          SHA: ${{ github.sha }}
        run: |
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"
          cd clo835_summer2023_assignment1
          docker build -t "$IMAGE_URI:latest" -t "$IMAGE_URI:$SHA" -f Dockerfile .
          docker push "$IMAGE_URI:latest"
          docker push "$IMAGE_URI:$SHA"

      - name: Build, tag, and push MYSQL image
        env:
          ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO: ${{ secrets.ECR_MYSQL_REPO }}
          SHA: ${{ github.sha }}
        run: |
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"
          cd clo835_summer2023_assignment1
          docker build -t "$IMAGE_URI:latest" -t "$IMAGE_URI:$SHA" -f Dockerfile_mysql .
          docker push "$IMAGE_URI:latest"
          docker push "$IMAGE_URI:$SHA"

